/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#14558f',
        'primary-light': '#4377A5',
        'primary-lighter': '#8AAAC7',
        'primary-lightest': '#E8EEF4',
        'primary-alt': '#388557',
        'primary-alt-lighter': '#9CC2AB',
        'primary-alt-lightest': '#D7E7DD',
        'primary-alt-dark': '#214F34',
        'highlight': '#f6c51b',
        'highlight-lighter': '#FBE28D',
        'highlight-lightest': '#FEF9E8',
        'error': '#CD0D0D',
        'error-lighter': '#EEACAC',
        'error-lightest': '#FCF3F3',
        'warning': '#f6c51b',
        'success': '#388557',
        'focus': '#3e94cf',
        'link': '#7299BC',
        'visited': '#772334',
        'font-base': '#141414',
        'font-detail': '#535353',
        'font-dark': '#141414',
        'font-medium': '#707070',
        'font-heading': '#141414',
        'font-inverse': 'white',
        'font-link': '#14558f',
        'font-error': '#CD0D0D',
        'bg': 'white',
        'bg-comp-title': '#535353',
        'bg-subtle': '#F2F2F2',
        'bg-section': '#F2F2F2',
        'bd': '#DCDCDC',
        'bd-divider': '#DCDCDC',
        'bd-divider-dark': '#535353',
        'bd-error': '#CD0D0D',
        'bd-input': '#707070',
      },
      fontFamily: {
        sans: ['Roboto', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
