/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx,html}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./public/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        "mf-primary": "#14558f",
        "mf-primary-light": "#4377A5",
        "mf-primary-lighter": "#8AAAC7",
        "mf-primary-lightest": "#E8EEF4",
        "mf-primary-alt": "#388557",
        "mf-primary-alt-lighter": "#9CC2AB",
        "mf-primary-alt-lightest": "#D7E7DD",
        "mf-primary-alt-dark": "#214F34",
        "mf-highlight": "#f6c51b",
        "mf-highlight-lighter": "#FBE28D",
        "mf-highlight-lightest": "#FEF9E8",
        "mf-error": "#CD0D0D",
        "mf-error-lighter": "#EEACAC",
        "mf-error-lightest": "#FCF3F3",
        "mf-warning": "#f6c51b",
        "mf-success": "#388557",
        "mf-focus": "#3e94cf",
        "mf-link": "#7299BC",
        "mf-visited": "#772334",
        "mf-font-base": "#141414",
        "mf-font-detail": "#535353",
        "mf-font-dark": "#141414",
        "mf-font-medium": "#707070",
        "mf-font-heading": "#141414",
        "mf-font-inverse": "#ffffff",
        "mf-font-link": "#14558f",
        "mf-font-error": "#CD0D0D",
        "mf-bg": "#ffffff",
        "mf-bg-comp-title": "#535353",
        "mf-bg-subtle": "#F2F2F2",
        "mf-bg-section": "#F2F2F2",
        "mf-bd": "#DCDCDC",
        "mf-bd-divider": "#DCDCDC",
        "mf-bd-divider-dark": "#535353",
        "mf-bd-error": "#CD0D0D",
        "mf-bd-input": "#707070",
        "mf-box-shadow-black": "rgba(0, 0, 0, 0.25)",
        // other aliases
        primary: "#14558f",
        "primary-light": "#4377A5",
        "primary-lighter": "#8AAAC7",
        "primary-lightest": "#E8EEF4",
        "primary-alt": "#388557",
        "primary-alt-lighter": "#9CC2AB",
        "primary-alt-lightest": "#D7E7DD",
        "primary-alt-dark": "#214F34",
        highlight: "#f6c51b",
        "highlight-lighter": "#FBE28D",
        "highlight-lightest": "#FEF9E8",
        error: "#CD0D0D",
        "error-lighter": "#EEACAC",
        "error-lightest": "#FCF3F3",
        warning: "#f6c51b",
        success: "#388557",
        focus: "#3e94cf",
        link: "#7299BC",
        visited: "#772334",
        "font-base": "#141414",
        "font-detail": "#535353",
        "font-dark": "#141414",
        "font-medium": "#707070",
        "font-heading": "#141414",
        "font-inverse": "#ffffff",
        "font-link": "#14558f",
        "font-error": "#CD0D0D",
        bg: "#ffffff",
        "bg-comp-title": "#535353",
        "bg-subtle": "#F2F2F2",
        "bg-section": "#F2F2F2",
        bd: "#DCDCDC",
        "bd-divider": "#DCDCDC",
        "bd-divider-dark": "#535353",
        "bd-error": "#CD0D0D",
        "bd-input": "#707070",
        "box-shadow-black": "rgba(0, 0, 0, 0.25)",
        "border-primary": "#14558f",
        "border-error": "#CD0D0D",
        "bg-gray-100": "#F3F4F6",
        "bg-gray-300": "#D1D5DB",
        "text-gray-400": "#9CA3AF",
        "text-gray-300": "#D1D5DB",
        "border-gray-200": "#E5E7EB",
        "hover-bg-error-lighter": "#EEACAC", // (optional alias)
        "ring-primary": "#14558f",
      },
      fontFamily: {
        sans: ["Roboto", "sans-serif"],
      },
    },
  },
  plugins: [],
};
