import { abbreviateTitle } from './titleAbbrev';

// Single source of truth for job titles throughout the app
export const jobTitleOptions: string[] = [
  'Administrator',
  'System Administrator',
  'IT Director',
  'Regional Administrator',
  'Program Director',
  'Assistant Program Director',
  'Assistant Program Administrator',
  'Assistant Facility Administrator',
  'Facility Administrator',
  'Director of Facility Operations',
  'Juvenile Justice Youth Development Specialist I',
  'Juvenile Justice Youth Development Specialist II',
  'Juvenile Justice Youth Development Specialist III',
  'Master Juvenile Justice Youth Development Specialist',
  'Youth Services Group Worker',
  'Clinical Social Worker I',
  'Clinical Social Worker II',
  'Clinical Social Worker Supervisor',
  'Psychologist',
  'Licensed Mental Health Counselor',
  'Director of Clinical Services',
  'Regional Clinical Coordinator',
  'Behavior Analyst',
  'Caseworker I',
  'Caseworker II',
  'Casework Supervisor',
  'Community Services Coordinator',
  'Regional Re-Entry Coordinator',
  'Regional Placement Coordinator',
  'Detention Coordinator',
  'Transport Officer',
  'Teacher',
  'Academic Instructor',
  'Special Education Teacher',
  'Education Coordinator',
  'Director of Education Programs',
  'Registered Nurse',
  'Nurse Practitioner',
  'Nursing Supervisor',
  'Medical Director',
  'Human Resources Generalist',
  'Human Resources Director',
  'Labor Relations Specialist',
  'Payroll & Time Administrator',
  'Budget Analyst',
  'Fiscal Manager',
  'General Counsel',
  'Attorney',
  'Deputy General Counsel',
  'Administrative Assistant',
  'Administrative Coordinator',
  'Training Specialist',
  'Director of Staff Development & Training',
  'Compliance Officer',
  'Licensing Coordinator',
  'Quality Assurance Manager',
  'Information Technology Specialist',
  'Network Administrator',
  'Systems Administrator',
  'IT Manager',
  'Director of Information Technology',
  'Chief Information Officer',
  'Regional Director',
  'Assistant Regional Director',
  'Deputy Commissioner',
  'Commissioner of DYS',
  'Chief of Staff',
  'Director of Operations',
  'Director of Policy & Program Development',
  'Supervisor',
  'Caseworker',
  'Program Staff',
  'Support Staff',
];

// Helper to format a title with its abbreviation for select menus or chips
export function titleWithAbbrev(title: string): string {
  return `${title} (${abbreviateTitle(title)})`;
}
